<#if (serviceAccount)?has_content>
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ${ocpNamespace}
  name: ${serviceAccount.name}
---
</#if>
<#list persitentVolumes as pv>
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ${ocpNamespace}
  name: pvc${pv.claim.name}
  labels:
    app: ${appName}
spec:
  accessModes:
    - ${pv.claim.accessModes}
  resources:
    requests:
      storage: ${pv.claim.gbStorage}Gi
  storageClassName: ${pv.claim.storageClassName}
---
</#list>

<#list configMaps as cm>
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: ${ocpNamespace}
  name: ${appName}${cm.name}
  labels:
    app: ${appName}
data:
 <#list cm.selectedKeyValue as itemcm>
  ${itemcm.keyName}: "${itemcm.value}"
 </#list>
---
  </#list>
  <#list configMapsAsvol as cm>
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: ${ocpNamespace}
  name: ${appName}${cm.name}
  labels:
    app: ${appName}
data:
 <#list cm.selectedKeyValue as itemcm>
  ${itemcm.keyName}: >-
    ${itemcm.value}
 </#list>
---
  </#list>
  <#list secrets as secret>
kind: Secret
apiVersion: v1
metadata:
  namespace: ${ocpNamespace}
  name: ${appName}${secret.name}
  labels:
    app: ${appName}    
data:
  <#list secret.selectedKeyValue as itemsecret>
  ${itemsecret.keyName}: ${itemsecret.value}
  </#list>  
type: Opaque
---
  </#list> 
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ${ocpNamespace}
  annotations:
    build-commit: '@git.commit.id.abbrev@'
    build-date: "@git.build.time@"
  name: ${appName}
  labels:
    app: ${appName}
spec:
  replicas: {{ocp-replicas}}
  selector:
    matchLabels:
      app: ${appName}
  template:
    metadata:
      name: ${appName}
      labels:
        app: ${appName}
      annotations:
        build-commit: '@git.commit.id.abbrev@'
        build-date: "@git.build.time@"
    spec:
      volumes:
   <#list emptyDirVolumes as emptyvol>
        - name: emptydir${emptyvol.name}
          emptyDir: {}
   </#list>
   <#list nas as nas>
        - name: nas${nas.name}
          nfs:
            server: ${nas.nas.server}
            path: ${nas.nas.serverPath}
   </#list>
   <#list persitentVolumes as pv>
        - name: pv${pv.name}
          persistentVolumeClaim:
            claimName: pvc${pv.claim.name}
   </#list>
   <#list configMapsAsvol as cm>
        - name: cm${cm.name}-vol
          configMap:
            name: ${appName}${cm.name}
            items:
            <#list cm.selectedKeyValue as itemcm>
              - key: ${itemcm.keyName}
                path: ${itemcm.keyName}
            </#list>
            defaultMode: 420
   </#list>
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: {{project.memory.request}}
              cpu : {{project.cpu.request}}
            limits:
              memory: {{project.memory.limit}}
              cpu : {{project.cpu.limit}}
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: Basic {{management.actuator.auth.basic.b64}}
          env:
<#list configMaps as cm>
   <#list cm.selectedKeyValue as itemcm>
            - name: ${itemcm.keyName}
              valueFrom:
                configMapKeyRef:
                  name: ${appName}${cm.name}
                  key: ${itemcm.keyName}
  </#list>
</#list>
<#list secrets as secret>
   <#list secret.selectedKeyValue as itemsecret>
            - name: ${itemsecret.keyName}
              valueFrom:
                secretKeyRef:
                  name: ${appName}${secret.name}
                  key: ${itemsecret.keyName}
   </#list>
</#list>
          ports:
            - containerPort: {{server.port}}
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
   <#list emptyDirVolumes as emptyvolmount>
            - name: emptydir${emptyvolmount.name}
              mountPath: ${emptyvolmount.path}
   </#list>
   <#list nas as nas>
            - name: nas${nas.name}
              mountPath: ${nas.path}
   </#list>
   <#list persitentVolumes as pv>
            - name: pv${pv.name}
              mountPath: ${pv.path}
   </#list>
   <#list cmVolumes as cmvol>
            - name: cm${cmvol.configMapName}-vol
              mountPath: ${cmvol.path}${cmvol.subPath}
   </#list>
<#if (serviceAccount)?has_content>
          securityContext:
            runAsUser: ${userUid}
</#if>
          image: >-
            {{ocp-cluster.registry}}/{{ocp-namespace}}/${appName}:@project.version@
<#if (serviceAccount)?has_content>
      serviceAccount: ${serviceAccount.name}
      securityContext:
        fsGroup: ${userGid}
        supplementalGroups: [${userGid}]
</#if>
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: ${appName}-service
  namespace: ${ocpNamespace}
  labels:
    spring-boot: 'true'
    spring-boot-env: {{bil.environment}}
    bil.com/env:  {{bil.environment}}
    user.name: {{bil.micro.actuator.username}}
    user.password: {{bil.micro.actuator.password}}
    app: ${appName}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{server.port}}
      targetPort: {{server.port}}
  selector:
    app: ${appName}
---
<#list routes as route>
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${appName}-route
  namespace: ${ocpNamespace}
  labels:
    app: ${appName}
spec:
  host: >-
    ${appName}-${appName}.{{bil.environment}}.{{cluster-suffix}}
  to:
    kind: Service
    name: ${appName}-service
    weight: 256
  port:
    targetPort: '{{server.port}}'
  tls:
    termination: edge
  wildcardPolicy: None
---
</#list>