<#list configMaps as cm>
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: ${ocpNamespace}
  name: ${appName}${cm.name}
  labels:
    app: ${appName}
data: <#if (cm.selectedKeyValue?size < 1)> {} </#if>
 <#list cm.selectedKeyValue as itemcm>
  ${itemcm.keyName}: "${itemcm.value}"
 </#list>
---
</#list>
<#list configMapsAsvol as cm>
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: ${ocpNamespace}
  name: ${appName}${cm.name}
  labels:
    app: ${appName}
data:
 <#list cm.selectedKeyValue as itemcm>
  ${itemcm.keyName}: >-
    ${itemcm.value}
 </#list>
---
</#list>