<#list secrets as secret>
kind: Secret
apiVersion: v1
metadata:
  namespace: ${ocpNamespace}
  name: ${appName}${secret.name}
  labels:
    app: ${appName}    
data:  <#if (secret.selectedKeyValue?size < 1)> {} </#if>
  <#list secret.selectedKeyValue as itemsecret>
  ${itemsecret.keyName}: ${itemsecret.value}
  </#list>  
type: Opaque
---
</#list> 